---
# =============================================================
# Clean Site Playbook - Removes app stack and image
#
# Usage:
#   ansible-playbook clean/playbooks/site.yml
# =============================================================

- import_playbook: remove_app.yml
- import_playbook: remove_image.yml
- import_playbook: remove_dynatrace_edgeconnect.yml
- import_playbook: remove_dynatrace_monaco.yml
- import_playbook: remove_dynatrace_api_config.yml
- import_playbook: remove_dynatrace_oneagent.yml
